#!/usr/bin/php
<?
include_once "conf.php";
# Thanks to http://drupal.org/node/27882

# Make a copy of new files in directory copy/
system("wget -N --restrict-file-names=windows,lowercase --adjust-extension --cut-dirs=2 -nH --mirror -p --html-extension --base=./ -k -P $source_path $SOURCE");

mkdir($strip_path);

include "strip_html.php";

# Thanks to http://blog.simlau.net/rsync-auf-einen-ftp-server.html

# Mountpoint anlegen
mkdir($dest_path);
 
# FTP Server per curlftpfs einhängen
system("curlftpfs $DESTINATION server");
 
# delete-after sorgt dafür das alte Dateien erst nach dem Transfer
# der neuen Dateien gelöscht werden.
system("rsync -a -T /tmp --delete-after stripped/ server/");
 
# FTP-Server unmounten
system("fusermount -u server");
